apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: [ "pods", "nodes", "services" ]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-tools-pod-reader-binding
  namespace: development
subjects:
  - kind: ServiceAccount
    name: internal-server
    namespace: development
  - kind: ServiceAccount
    name: dev-tools
    namespace: development
  - kind: ServiceAccount
    name: file-server
    namespace: development

roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

