#!/bin/bash
NAMESPACE="development"

DEV_TOOLS_CONTAINER="$(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=dev-tools -o jsonpath='{.items[0].metadata.name}')"

kubectl exec -n $NAMESPACE -it "$DEV_TOOLS_CONTAINER" -- bash
