apiVersion: v1
kind: Pod
metadata:
  name: pvc-transfer-pod-v1
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "cp -r /source/* /mnt/ && tail -f /dev/null"]
      volumeMounts:
        - name: storage-pv
          mountPath: /mnt/internal-server/config
        - name: source-volume
          mountPath: /source
  volumes:
    - name: storage-pv
      persistentVolumeClaim:
        claimName: storage-pv
    - name: source-volume
      hostPath:
        path: ./internal-server/config
        type: Directory
  restartPolicy: Never
