apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspect-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c", "cp -r /source/* /mnt/" ]
      volumeMounts:
        - name: config-pvc
          mountPath: /mnt/internal-server/config
        - name: source-volume
          mountPath: /source
  volumes:
    - name: config-pvc
      persistentVolumeClaim:
        claimName: config-pvc
    - name: source-volume
      hostPath:
        path: ./internal-server/config
        type: Directory
  restartPolicy: Never
