#!/bin/bash

NAMESPACE="development"
PROXY_SERVER_CONTAINER="$(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=internal-server -o jsonpath='{.items[0].metadata.name}')"

echo "Connecting to the proxy server container in the '$PROXY_SERVER_CONTAINER' pod..."

kubectl logs -n $NAMESPACE -f --since=12h --tail=1000000 --prefix=true --max-log-requests=15 -lapp.kubernetes.io/name=internal-server
