#!/bin/bash

NAMESPACE="development"
DEV_TOOLS_CONTAINER="$(kubectl get pods -n $NAMESPACE -l app.kubernetes.io/name=dev-tools -o jsonpath='{.items[0].metadata.name}')"

kubectl exec -n $NAMESPACE "$DEV_TOOLS_CONTAINER" -- curl -s "file-server:80800/api/file-server/v1/v3/api-docs"
