#!/bin/bash

source ./k8s-setup-utils

# Create master nodes
for i in $(seq 1 "$NUM_MASTERS"); do
    MASTER_NAME="${BASE_NAME}-master-${i}-${CLUSTER_VERSION}"
    echo "Creating master node: $MASTER_NAME"
    multipass launch --name "$MASTER_NAME" --memory "$MASTER_MEM" --cpus "$MASTER_CPUS" --disk "$MASTER_DISK" --cloud-init ./template/k8s-base.yaml
    # shellcheck disable=SC2206
    MASTER_NODES+=($MASTER_NAME)
done

# Create worker nodes
for i in $(seq 1 "$NUM_WORKERS"); do
    WORKER_NAME="${BASE_NAME}-worker-${i}-${CLUSTER_VERSION}"
    echo "Creating worker node: $WORKER_NAME"
    multipass launch --name "$WORKER_NAME" --memory "$WORKER_MEM" --cpus "$WORKER_CPUS" --disk "$WORKER_DISK" --cloud-init ./template/k8s-base.yaml
    # shellcheck disable=SC2206
    WORKER_NODES+=($WORKER_NAME)
done

# Create HAProxy node
HAPROXY_NAME="${BASE_NAME}-haproxy-${CLUSTER_VERSION}"
echo "Creating HAProxy node: $HAPROXY_NAME"
multipass launch --name "$HAPROXY_NAME" --memory 1G --cpus 1 --disk 5G

## Install HAProxy
multipass exec "$HAPROXY_NAME" -- bash -c "
    sudo apt-get update && sudo apt-get install -y haproxy
"

# Get HAProxy IP address
HAPROXY_IP=$(get_ip_address "$HAPROXY_NAME")

# Generate HAProxy configuration
multipass exec "$HAPROXY_NAME" -- sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy-bk.cfg

cat <<EOF | multipass exec "$HAPROXY_NAME" -- sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# K8s config
frontend kubernetes
    mode tcp
# shellcheck disable=SC2086
$(config_haproxy_ip_address "$HAPROXY_IP")
    option tcplog
    default_backend k8s-masters

backend k8s-masters
    mode tcp
    balance roundrobin
    option tcp-check
EOF

# Add master nodes to HAProxy configuration
for i in "${!MASTER_NODES[@]}"; do
    MASTER_IP=$(get_ip_address "${MASTER_NODES[$i]}")
    config_master_ip_address "$MASTER_IP" "$i" | multipass exec "$HAPROXY_NAME" -- sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
done

# Update /etc/hosts for all nodes
for node in "${MASTER_NODES[@]}" "${WORKER_NODES[@]}"; do
    echo "Updating /etc/hosts on $node"
    multipass exec "$node" -- bash -c "echo '${HAPROXY_IP} ${HAPROXY_NAME}' | sudo tee -a /etc/hosts"
done

# Restart HAProxy to apply the new configuration
multipass exec "$HAPROXY_NAME" -- sudo systemctl restart haproxy

multipass exec "$HAPROXY_NAME" -- sudo systemctl status haproxy --no-pager

echo "Cluster setup is complete."

echo "Run 'sudo su' into a master node, after and run commands below to initialize the cluster

    kubeadm init --control-plane-endpoint $HAPROXY_NAME:6443 --upload-certs

    kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    kubectl get nodes
"

