apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: file-server
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-server
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
