apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-server-config
data:
  CONFIG_BASE_PATH: "/mnt/internal-server/config"
  HTTPS_ENABLE: "false"
  LOGSTASH_URI: "logstash:5000"
  LOGSTASH_ENABLED: "false"
