image:
  repository: eliasmeireles/file-server
  pullPolicy: IfNotPresent
  tag: "v1"

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: { }
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  example.com/annotation-key: "value"

podSecurityContext: { }
securityContext: { }

labels:
  app: file-server

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  nodePort: 30018

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: k8s.local.service
      paths:
        - path: /api/file-server/v1/
          pathType: Prefix
  tls:

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 10

nodeSelector:
  kubernetes.io/os: linux

tolerations: [ ]

affinity: { }

networkPolicy:
  enabled: true
  name: allow-file-server-traffic
  namespace: default
  labels:
    app: file-server
  ingress:

deployment:
  metadata:
    labels:
      app: file-server
