apiVersion: v1
kind: Service
metadata:
  name: {{ include "internal-server.fullname" . }}
  labels:
    {{- include "internal-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    {{- include "internal-server.selectorLabels" . | nindent 4 }}
