kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
