#!/bin/bash

set -e


source ../scripts/log-utils

setup_logs "prometheus-monitor-installer"

CONTENT_PATH=$(pwd)

cd .temp

run_monitor_installer() {

  rm -rf kube-prometheus || true

  git clone https://github.com/prometheus-operator/kube-prometheus

  cd kube-prometheus

  kubectl create -f manifests/setup || true

  log "Updating grafana network policy with ${CONTENT_PATH}/grafana-networkPolicy.yaml"

  cp "${CONTENT_PATH}/grafana-networkPolicy.yaml" manifests/

  log "Loading grafana ingress with ${CONTENT_PATH}/grafana-ingress.yaml"

  cp "${CONTENT_PATH}/grafana-ingress.yaml" manifests/

  kubectl apply -f manifests/

  kubectl get pods -n monitoring

  log "Prometheus and Grafana installed successfully"

  log "You can try to run command bellow to access Grafana dashboard on http://localhost:3000

    kubectl port-forward -n monitoring svc/grafana 3000:3000
  "

  log "You can also configure your local DNS to access Grafana dashboard on http://monitor.k8s.learning.local

    echo \"<k8s proxy ip address> monitor.k8s.learning.local\" | sudo tee -a /etc/hosts
    "

  rm -rf "${CONTENT_PATH}/kube-prometheus"
  exit 1
}

run_monitor_installer
