#!/bin/bash

source ./scripts/log-utils

setup_logs "rancher-installer"

# Default values
INSTANCE_NAME="k8s-rancher"
DEFAULT_MEM=8G
DEFAULT_CPUS=4
DEFAULT_DISK=50G

# Function to display usage information
usage() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --name     Name of the Multipass instance (default: $INSTANCE_NAME)"
    echo "  --cpu      Number of CPUs (default: $DEFAULT_CPUS)"
    echo "  --memory   Memory in GB (default: $DEFAULT_MEM)"
    echo "  --disk     Disk size (default: $DEFAULT_DISK)"
    exit 1
}

# Initialize variables with default values
NAME="$INSTANCE_NAME"
CPUS="$DEFAULT_CPUS"
MEMORY="$DEFAULT_MEM"
DISK="$DEFAULT_DISK"

# Parse command-line arguments
while [ $# -gt 0 ]; do
    case "$1" in
        --name)
            NAME="$2"
            shift 2
            ;;
        --cpu)
            CPUS="$2"
            shift 2
            ;;
        --memory)
            MEMORY="$2"
            shift 2
            ;;
        --disk)
            DISK="$2"
            shift 2
            ;;
        --help)
            usage
            ;;
        -h)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

log "Installing Rancher on Multipass instance '$NAME' with $CPUS CPUs, $MEMORY memory, and $DISK disk size."

# Launch Multipass instance with specified or default parameters
multipass launch --name "$NAME" --cpus "$CPUS" --memory "$MEMORY" --disk "$DISK" --cloud-init ./template/k8s-rancher.yaml

# Access the instance to retrieve the Rancher container password
log "Retrieving Rancher initial password..."
multipass exec "$NAME" -- bash -c "
    echo 'Waiting for Rancher container to initialize...'
    until sudo docker ps | grep -q 'rancher/rancher'; do sleep 5; done
    echo ''
    echo 'Loading Bootstrap Password. Sleeping for 60 seconds to allow Rancher to initialize...'
    sleep 60
    sudo docker logs rancher-server 2>/dev/null | grep -A1 'Bootstrap Password:'
    echo ''
"

RANCHER_HOST="https://$(get_ip_address "$NAME")"

# Open Rancher URL in the default browser without blocking the script
open "$RANCHER_HOST" &>/dev/null &

log "Multipass instance '$NAME' created successfully."
log "Access Rancher at: $RANCHER_HOST"





