apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-request
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-request
  template:
    metadata:
      labels:
        app: http-request
    spec:
      containers:
        - name: http-request
          image: eliasmeireles/http-request
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-request
spec:
  type: NodePort
  selector:
    app: http-request
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-request
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-request
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
